spring:
  data:
    mongodb:
      database: game_accountant
      host: localhost
      port: 27017
  security.oauth2.client.registration.google:
    client-id: TODO
    client-secret: TODO

game:
  cors:
    http:
      allowedOrigins: http://localhost:4200
      allowedMethods: PATCH, GET, POST, DELETE, OPTIONS, PUT
